project:
  type: website

website:
  title: "Benjamin Jacobs"
  search: FALSE
  navbar:
    title: Benjamin Jacobs
    # logo: "headshot1.jpg"
    search: FALSE
    background: "#331800"
    left:
      - href: index.qmd
        text: Home
      - href: CV_Resume.qmd
        text: CV/Resume
      - Publications.qmd
      - Miscellanea.qmd
  sidebar: 
    logo: "headshot1.jpg"
    background: "#F0F0F0"
    search: FALSE
  page-footer:
    foreground: "#331800"
    background: "#F0F0F0"
    center: "&copy; MMXXIII Benjamin Jacobs"
        

format:
  html:
    # theme: cosmo
    css: styles.css
    toc: false



